id = "realpaver-language"
name = "realpaver"
version = "0.0.2"
schema_version = 1
authors = ["Raphaël Chenouard <raphael.chenouard@ec-nantes.fr>"]
description = "Grammar and syntax highlighting for RealPaver files."
repository = "https://gitlab.univ-nantes.fr/realpavergroup/zed-realpaver"

[grammars.realpaver]
# repository = "file://Users/user/Boulot/dev/tree-sitter-realpaver"
repository = "https://github.com/realpaver/tree-sitter-realpaver"
commit = "baf9f588d251be0d2ddf6da107c0a907974e31f2"
