name = "RealPaver"
grammar = "realpaver"
path_suffixes = ["rp"]
line_comments = ["# "]
brackets = [
    { start = "\"", end = "\"", close = false, newline = false },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
]
tab_size = 2
